### PR TITLE
Add simulation repo to demo workspace for the nav2 demo (#201)

### LINKED ISSUE #201: Simulation resources are not available for the Nav2 Demo
### Version or commit hash

main

### RMW Implementation

FastRTPS

### Steps to reproduce issue

Run the nav2 demo, the robot model does not appear in the rviz widget because the meshes are not available in the container. This I believe is an old issue unrelated to the recent change, just noticed it while testing.

### Expected behavior

Would like to see the rover for visualization purposes.

### Actual behavior

We only get tf and a geometry error saying the mesh files cannot be found.

image

### Backtrace or Console output

e.g.

```
[rviz2-1] [ERROR] [1729629168.366980218] [rviz2]: Could not load resource [package://simulation/models/curiosity_
path/meshes/suspension_arm_F_L_fixed.dae]: Unable to open file "package://simulation/models/curiosity_path/meshes/suspension_arm_F_L_fixed.dae".                                                                                  
[rviz2-1] [ERROR] [1729629168.371587640] [rviz2]: Could not load resource [package://simulation/models/curiosity_path/meshes/suspension_arm_F_L_fixed.dae]: Unable to open file "package://simulation/models/curiosity_path/meshes
/suspension_arm_F_L_fixed.dae".    
```

### PR DESCRIPTION
**Pull request by eholum**
Resolves #201

Not sure how much this matters, but the rover doesn't show up in the nav2 rviz panel because the simulation resources are not available in the demo container. I also hate to add more vcs repos to our toolsets, but figured this was simplest since every other demo is built in the same way.

### CODE REVIEW

**Comment by eholum** [comment]
@xfiderek you most recently poked at this, do you think this is actually necessary?

**Comment by xfiderek** [comment]
Hey @eholum. In general the demo should be working (you should be able to control rover with nav2 via RVIZ), but I believe you mean that the rover's URDF visualization is not present, right? Indeed, that won't work in the current state.  To make it work you could run rviz from space_robots container, but then you won't be able to use nav2 plugin.

In general I plan to rework nav2_demo, so that rviz container is completely separate from the nav2 container (as part of https://github.com/space-ros/demos/issues/28). We could upload simulation assets to the rviz container then. If you urgently need this feature I am personally fine with merging it, but otherwise make it makes sense to first carve out rviz. What do you think?

**Comment by eholum** [comment]
> but I believe you mean that the rover's URDF visualization is not present in rviz, right?

Yeah that's exactly right. I was just expecting it to render and it didn't, it's a low priority, but since we're wrapping up the humble release it's just a "nice to have" to make the released version slightly more complete.

**Comment by eholum** [comment]
Closing this given the discussion above.

**Pull request closed without merging**
